agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.8.5 ucx/1.13.1_cuda-11.2 cuda/11.2 openmpi/4.1.5_cuda-11.2 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_CUDA_USE_BINARYBUILDER: false
  JULIA_CUDA_MEMORY_POOL: none
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Run"
    steps:

      - label: ":computer: steady state"
        key: "cpu_steadystate"
        command:
          - >
            nsys profile --trace=nvtx --output=output/cpu_steadystate/report
            ./shallowwater --output-dir=output/cpu_steadystate
          - ./create-movie --output-dir=output/cpu_steadystate --filename=output/cpu_steadystate/out.mp4
        artifact_paths:
          - output/cpu_steadystate/report.*
          - output/cpu_steadystate/out.mp4

      - label: ":computer: :mpi: steady state"
        key: "cpu_mpi_steadystate"
        command:
          - >
            srun --cpu-bind=cores
            nsys profile --trace=nvtx,mpi  --mpi-impl=openmpi --output=output/cpu_mpi_steadystate/report-%q{PMI_RANK} 
            ./shallowwater --output-dir=output/cpu_mpi_steadystate
          - nsys-mkview output/cpu_mpi_steadystate
          - nsys-archive output/cpu_mpi_steadystate
          - ./create-movie --output-dir=output/cpu_mpi_steadystate --filename=output/cpu_mpi_steadystate/out.mp4
        artifact_paths:
          - output/cpu_mpi_steadystate/out.mp4
        agents:
          slurm_ntasks: 4
          slurm_cpus_per_task: 2

      - label: ":flower_playing_cards: steady state"
        key: "gpu_steadystate"
        command:
          - >
            nsys profile --trace=nvtx,cuda --output=output/gpu_steadystate/report
            ./shallowwater --output-dir=output/gpu_steadystate
          - ./create-movie --output-dir=output/gpu_steadystate --filename=output/gpu_steadystate/out.mp4
        artifact_paths:
          - output/gpu_steadystate/report.*
          - output/gpu_steadystate/out.mp4
        agents:
          slurm_gpus: 1

      - label: ":flower_playing_cards: :mpi: steady state"
        key: "gpu_mpi_steadystate"
        command:
          - >
            srun --cpu-bind=cores --gpu-bind=none
            ./shallowwater --output-dir=output/gpu_mpi_steadystate
          - nsys-mkview output/gpu_mpi_steadystate
          - nsys-archive output/gpu_mpi_steadystate
          - ./create-movie --output-dir=output/gpu_mpi_steadystate --filename=output/gpu_mpi_steadystate/out.mp4
        env:
          OMPI_MCA_btl_base_verbose: 10
          OMPI_MCA_pml_base_verbose: 10
          UCX_LOG_LEVEL: info
        artifact_paths:
          - output/gpu_mpi_steadystate/nsys.tar.gz
          - output/gpu_mpi_steadystate/out.mp4
        agents:
          slurm_ntasks: 4
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 2
