agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.8.5 openmpi/4.1.1 cuda/11.3 hdf5/1.12.1-ompi411 nsight-systems/2022.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_CUDA_USE_BINARYBUILDER: false
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Run"
    steps:

      - label: ":computer: steady state"
        key: "cpu_steadystate"
        command:
          - nsys profile --trace=nvtx --output=output/cpu_steadystate/report ./shallowwater --output-dir=output/cpu_steadystate
          - ./create-movie --output-dir=output/cpu_steadystate --filename=output/cpu_steadystate/out.mp4
        artifact_paths:
          - output/cpu_steadystate/report.*
          - output/cpu_steadystate/out.mp4

      - label: ":computer: MPI steady state"
        key: "cpu_mpi_steadystate"
        command:
          - srun ./shallowwater --output-dir=output/cpu_mpi_steadystate
          - ./create-movie --output-dir=output/cpu_mpi_steadystate --filename=output/cpu_mpi_steadystate/out.mp4
        artifact_paths:
          - output/cpu_mpi_steadystate/out.mp4
        agents:
          slurm_ntasks: 4

      - label: ":flower_playing_cards: steady state"
        key: "gpu_steadystate"
        command:
          - nsys profile --trace=nvtx,cuda --output=output/gpu_steadystate/report ./shallowwater --output-dir=output/gpu_steadystate
          - ./create-movie --output-dir=output/gpu_steadystate --filename=output/gpu_steadystate/out.mp4
        artifact_paths:
          - output/gpu_steadystate/report.*
          - output/gpu_steadystate/out.mp4
        agents:
          slurm_gpus: 1

      - label: ":flower_playing_cards: Rossby-Haurwitz"
        key: "gpu_rossbyhaurwitz_res"
        command:
          - ./shallowwater --output-dir=output/gpu_rossbyhaurwitz_res --panel-size=32 --time-step=60 --time-end=1728000
          - ./create-movie --output-dir=output/gpu_rossbyhaurwitz_res --filename=output/gpu_rossbyhaurwitz_res/out.mp4
        artifact_paths:
          - output/gpu_rossbyhaurwitz_res/out.mp4
        agents:
          slurm_gpus: 1
