agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.8.5 ucx/1.13.1_cuda-11.2 cuda/11.2 openmpi/4.1.5_cuda-11.2 hdf5/1.14.0-ompi415 nsight-systems/2022.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_CUDA_USE_BINARYBUILDER: false
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Run"
    steps:

      - label: ":computer: steady state"
        key: "cpu_steadystate"
        command:
          - nsys profile --trace=nvtx --output=output/cpu_steadystate/report ./shallowwater --output-dir=output/cpu_steadystate
          - ./create-movie --output-dir=output/cpu_steadystate --filename=output/cpu_steadystate/out.mp4
        artifact_paths:
          - output/cpu_steadystate/report.*
          - output/cpu_steadystate/out.mp4

      - label: ":computer: :mpi: steady state"
        key: "cpu_mpi_steadystate"
        command:
          - srun ./shallowwater --output-dir=output/cpu_mpi_steadystate
          - ./create-movie --output-dir=output/cpu_mpi_steadystate --filename=output/cpu_mpi_steadystate/out.mp4
        artifact_paths:
          - output/cpu_mpi_steadystate/out.mp4
        agents:
          slurm_ntasks: 4

      - label: ":flower_playing_cards: steady state"
        key: "gpu_steadystate"
        command:
          - nsys profile --trace=nvtx,cuda --output=output/gpu_steadystate/report ./shallowwater --output-dir=output/gpu_steadystate
          - ./create-movie --output-dir=output/gpu_steadystate --filename=output/gpu_steadystate/out.mp4
        artifact_paths:
          - output/gpu_steadystate/report.*
          - output/gpu_steadystate/out.mp4
        agents:
          slurm_gpus: 1

      - label: ":flower_playing_cards: :mpi: steady state"
        key: "gpu_mpi_steadystate"
        command:
          - >
            srun --cpu-bind=cores --gpu-bind=per_task:1
            nsys profile --trace=nvtx,cuda,mpi --mpi-impl=openmpi --output=gpu_mpi_steadystate/report-multi-%q{PMI_RANK} 
            ./shallowwater --output-dir=output/gpu_mpi_steadystate
          - ./create-movie --output-dir=output/gpu_mpi_steadystate --filename=output/gpu_mpi_steadystate/out.mp4
        artifact_paths:
          - output/gpu_mpi_steadystate/report-multi*
          - output/gpu_mpi_steadystate/out.mp4
        agents:
          slurm_ntasks: 4
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 2

      - label: ":flower_playing_cards: Mountain"
        key: "gpu_mountain"
        command:
          - ./shallowwater mountain --output-dir=output/gpu_mountain --time-end=172800
          - ./create-movie --output-dir=output/gpu_mountain --filename=output/gpu_mountain/out.mp4
        artifact_paths:
          - output/gpu_mountain/out.mp4
        agents:
          slurm_gpus: 1

      - label: ":flower_playing_cards: Rossby-Haurwitz"
        key: "gpu_rossbyhaurwitz_res"
        command:
          - ./shallowwater rossbyhaurwitz --output-dir=output/gpu_rossbyhaurwitz_res --panel-size=32 --time-step=60 --time-end=172800
          - ./create-movie --output-dir=output/gpu_rossbyhaurwitz_res --filename=output/gpu_rossbyhaurwitz_res/out.mp4
        artifact_paths:
          - output/gpu_rossbyhaurwitz_res/out.mp4
        agents:
          slurm_gpus: 1

      - label: ":flower_playing_cards: barotropic instability"
        key: "gpu_barotropicinstability"
        command:
          - ./shallowwater barotropicinstability --time-end=1728000 --output-nsteps=20 --output-dir=output/gpu_barotropicinstability
          - ./create-movie --output-dir=output/gpu_barotropicinstability --filename=output/gpu_barotropicinstability/out.mp4
        artifact_paths:
          - output/gpu_barotropicinstability/out.mp4
        agents:
          slurm_gpus: 1
